<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Adaptive.Intelligence.Framework</AssemblyName>
    <AssemblyTitle>Adaptive Intelligence .NET Framework</AssemblyTitle>
    <RootNamespace>Adaptive.Intelligence</RootNamespace>
    <ApplicationIcon>AI.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Sam.Jones.Adaptive.Intelligence.Framework.v11</PackageId>
    <Title>Adaptive Intelligence .NET Framework 11</Title>
    <Version>11.0.1.0</Version>
	<AssemblyVersion>11.0.1.0</AssemblyVersion>
	<AnalyzeAssembly>True</AnalyzeAssembly>
	<FileVersion>11.0.1.0</FileVersion>
    <Authors>Sam Jones</Authors>
    <Product>Adaptive Intelligence .NET Framework</Product>
    <Description>A general-purpose, portable .NET class library for application development on .NET 11</Description>
    <Copyright>Copyright © 2024 - 2026 by Sam Jones.  All rights reserved.</Copyright>
    <PackageProjectUrl>https://samjones.azurewebsites.net</PackageProjectUrl>
    <Platforms>AnyCPU;x64</Platforms>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
    <ReadyToRun>true</ReadyToRun>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>False</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <IsTrimmable>False</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsTrimmable>False</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <IsTrimmable>False</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\AmEx.jpg" />
    <None Remove="Resources\China Union Pay.jpg" />
    <None Remove="Resources\Diners Club.jpg" />
    <None Remove="Resources\Discover.jpg" />
    <None Remove="Resources\Generic Card.jpg" />
    <None Remove="Resources\Maestro.png" />
    <None Remove="Resources\MasterCard.jpg" />
    <None Remove="Resources\Visa.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AI.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AmEx.jpg" />
    <EmbeddedResource Include="Resources\China Union Pay.jpg" />
    <EmbeddedResource Include="Resources\Diners Club.jpg" />
    <EmbeddedResource Include="Resources\Discover.jpg" />
    <EmbeddedResource Include="Resources\Generic Card.jpg" />
    <EmbeddedResource Include="Resources\Maestro.png" />
    <EmbeddedResource Include="Resources\MasterCard.jpg" />
    <EmbeddedResource Include="Resources\Visa.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
