//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaptive.Intelligence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adaptive.Intelligence.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AmEx {
            get {
                object obj = ResourceManager.GetObject("AmEx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] China_Union_Pay {
            get {
                object obj = ResourceManager.GetObject("China_Union_Pay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Diners_Club {
            get {
                object obj = ResourceManager.GetObject("Diners_Club", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Discover {
            get {
                object obj = ResourceManager.GetObject("Discover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The hash data does not match the original. This data may have been modified.&quot;.
        /// </summary>
        internal static string ErrorBadHash {
            get {
                return ResourceManager.GetString("ErrorBadHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be decrypted..
        /// </summary>
        internal static string ErrorCantDecrypt {
            get {
                return ResourceManager.GetString("ErrorCantDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption failed, resulting in a null value..
        /// </summary>
        internal static string ErrorCantEncrypt {
            get {
                return ResourceManager.GetString("ErrorCantEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified object is not the same type as this instance..
        /// </summary>
        internal static string ErrorCompareInvalidType {
            get {
                return ResourceManager.GetString("ErrorCompareInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key content length..
        /// </summary>
        internal static string ErrorInvalidKeyContentLength {
            get {
                return ResourceManager.GetString("ErrorInvalidKeyContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys have not been initialized..
        /// </summary>
        internal static string ErrorKeysNotInitialized {
            get {
                return ResourceManager.GetString("ErrorKeysNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text was supplied for parsing..
        /// </summary>
        internal static string ErrorMessageCantParseTime {
            get {
                return ResourceManager.GetString("ErrorMessageCantParseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse a null or empty string into a time value..
        /// </summary>
        internal static string ErrorMessageNullTime {
            get {
                return ResourceManager.GetString("ErrorMessageNullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream was not open, or not opened for reading..
        /// </summary>
        internal static string ErrorNotOpenForRead {
            get {
                return ResourceManager.GetString("ErrorNotOpenForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream was not open, or not opened for writing..
        /// </summary>
        internal static string ErrorNotOpenForWrite {
            get {
                return ResourceManager.GetString("ErrorNotOpenForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from stream..
        /// </summary>
        internal static string ErrorStreamRead {
            get {
                return ResourceManager.GetString("ErrorStreamRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to stream..
        /// </summary>
        internal static string ErrorStreamWrite {
            get {
                return ResourceManager.GetString("ErrorStreamWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Generic_Card {
            get {
                object obj = ResourceManager.GetObject("Generic_Card", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Maestro {
            get {
                object obj = ResourceManager.GetObject("Maestro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MasterCard {
            get {
                object obj = ResourceManager.GetObject("MasterCard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Visa {
            get {
                object obj = ResourceManager.GetObject("Visa", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
